version: 2.1
jobs:
    build_windows:
        docker:
            - image: electronuserland/builder:wine
        steps:
            - checkout
            - run:
                  name: Install dependencies
                  command: |
                      npm install --save
            - run:
                  name: Build application
                  command: |
                      npm run dist
            - run:
                  name: Output file system
                  command: |
                      ls -l -f -R -a ./dist
            - store_artifacts:
                  path: ./dist/Installer.exe
workflows:
    build:
        jobs:
            - build_windows
